In [9]:
import pandas as pd
import numpy as np
df = pd.read_csv('/Users/merryxmm7/Documents/GitHub/SQL-Quest/MbasedonV.csv')
df

,Title,Direction,Release date,Worldwide box office,Rotten Tomatoes,Metacritic,Distributor,Original game publisher
0,Super Mario Bros.,Rocky MortonAnnabel Jankel,"may 28, 1993","$38,912,465[1]",29%[2],35/100[3],Buena Vista Pictures Distribution,Nintendo
1,Double Dragon,James Yukich,"November 4, 1994","$4,152,699[a]",12%[4],NaN,Gramercy Pictures,Technōs Japan
2,Street Fighter,Steven E. de Souza,"December 23, 1994","$99,423,521[5]",11%[6],34/100[7],Universal PicturesColumbia TriStar Film Distri...,Capcom
3,Mortal Kombat,Paul W. S. Anderson,"August 18, 1995","$124,741,822[b]",45%[8],60/100[9],New Line Cinema,Midway
4,Mortal Kombat Annihilation,John R. Leonetti,"November 21, 1997","$51,376,861[10]",4%[11],11/100[12],NaN,NaN
...,...,...,...,...,...,...,...,...
82,Fate/stay night: Heaven's Feel II. lost butterfly,Tomonori Sudō,"January 12, 2019","$19,790,000[239]",NaN,NaN,Aniplex,Type-Moon
83,Pokémon: Mewtwo Strikes Back Evolution,Kunihiko YuyamaMotonori Sakakibara,"July 12, 2019","¥2,980,000,000[226]",NaN,NaN,TohoViz Media,Nintendo
84,NiNoKuni,Yoshiyuki Momose,"August 23, 2019","$2,000,000",NaN,NaN,"OLM, Inc.",Bandai Namco Entertainment
85,Fate/stay night: Heaven's Feel III. spring song,Tomonori Sudō,"March 28, 2020","$19,252,497",NaN,NaN,Aniplex,Type-Moon
86,Pokémon the Movie: Secrets of the Jungle,Tetsuo Yajima,"December 25, 2020","$23,600,000",NaN,NaN,TohoViz Media,Nintendo

In [10]:
# Remove everything after and including the first "[" in the "Worldwide box office" column
df['Worldwide box office'] = df['Worldwide box office'].str.split('[', n=1).str[0]
# Remove the format after the ratings in the "Rotten Tomatoes" column
df['Rotten Tomatoes'] = df['Rotten Tomatoes'].str.split('[', n=1).str[0]
# Remove the format after the ratings in the "Metacritic" column
df['Metacritic'] = df['Metacritic'].str.split('[', n=1).str[0]

In [11]:
# Define the exchange rate
exchange_rate = 154.62

# Function to convert yen to dollars
def convert_to_usd(amount):
    if '¥' in str(amount):  # Convert to string to handle floats
        yen_amount = float(str(amount).replace('¥', '').replace(',', ''))
        return "${:,.2f}".format(yen_amount / exchange_rate)
    else:
        return amount

# Apply the conversion function to the "Worldwide box office" column
df['Worldwide box office'] = df['Worldwide box office'].apply(convert_to_usd)

In [12]:
# Display the updated DataFrame
df['Worldwide box office']

0        $38,912,465
1         $4,152,699
2        $99,423,521
3       $124,741,822
4        $51,376,861
           ...
82       $19,790,000
83    $19,273,056.53
84        $2,000,000
85       $19,252,497
86       $23,600,000
Name: Worldwide box office, Length: 87, dtype: object

In [13]:
df

,Title,Direction,Release date,Worldwide box office,Rotten Tomatoes,Metacritic,Distributor,Original game publisher
0,Super Mario Bros.,Rocky MortonAnnabel Jankel,"may 28, 1993","$38,912,465",29%,35/100,Buena Vista Pictures Distribution,Nintendo
1,Double Dragon,James Yukich,"November 4, 1994","$4,152,699",12%,NaN,Gramercy Pictures,Technōs Japan
2,Street Fighter,Steven E. de Souza,"December 23, 1994","$99,423,521",11%,34/100,Universal PicturesColumbia TriStar Film Distri...,Capcom
3,Mortal Kombat,Paul W. S. Anderson,"August 18, 1995","$124,741,822",45%,60/100,New Line Cinema,Midway
4,Mortal Kombat Annihilation,John R. Leonetti,"November 21, 1997","$51,376,861",4%,11/100,NaN,NaN
...,...,...,...,...,...,...,...,...
82,Fate/stay night: Heaven's Feel II. lost butterfly,Tomonori Sudō,"January 12, 2019","$19,790,000",NaN,NaN,Aniplex,Type-Moon
83,Pokémon: Mewtwo Strikes Back Evolution,Kunihiko YuyamaMotonori Sakakibara,"July 12, 2019","$19,273,056.53",NaN,NaN,TohoViz Media,Nintendo
84,NiNoKuni,Yoshiyuki Momose,"August 23, 2019","$2,000,000",NaN,NaN,"OLM, Inc.",Bandai Namco Entertainment
85,Fate/stay night: Heaven's Feel III. spring song,Tomonori Sudō,"March 28, 2020","$19,252,497",NaN,NaN,Aniplex,Type-Moon
86,Pokémon the Movie: Secrets of the Jungle,Tetsuo Yajima,"December 25, 2020","$23,600,000",NaN,NaN,TohoViz Media,Nintendo

In [14]:


# Fill NaN values with "UNKNOWN" for specified columns
df['Title'].fillna('UNKNOWN', inplace=True)
df['Direction'].fillna('UNKNOWN', inplace=True)
df['Distributor'].fillna('UNKNOWN', inplace=True)
df['Original game publisher'].fillna('UNKNOWN', inplace=True)

# Fill NaN values with 0 for "Rotten Tomatoes" and "Metacritic" columns
df['Rotten Tomatoes'].fillna('0%', inplace=True)
df['Metacritic'].fillna('0/100', inplace=True)

# Remove percentage sign from "Rotten Tomatoes" column and convert to numeric type
df['Rotten Tomatoes'] = df['Rotten Tomatoes'].str.rstrip('%').replace('N/A', np.nan).astype(float)

# Remove everything after "/" from "Metacritic" column and convert to numeric type
def extract_metacritic(score):
    try:
        return int(score.split('/')[0])
    except (AttributeError, ValueError):
        return np.nan

df['Metacritic'] = df['Metacritic'].apply(extract_metacritic)

In [16]:
df

,Title,Direction,Release date,Worldwide box office,Rotten Tomatoes,Metacritic,Distributor,Original game publisher
0,Super Mario Bros.,Rocky MortonAnnabel Jankel,"may 28, 1993","$38,912,465",29.0,35.0,Buena Vista Pictures Distribution,Nintendo
1,Double Dragon,James Yukich,"November 4, 1994","$4,152,699",12.0,0.0,Gramercy Pictures,Technōs Japan
2,Street Fighter,Steven E. de Souza,"December 23, 1994","$99,423,521",11.0,34.0,Universal PicturesColumbia TriStar Film Distri...,Capcom
3,Mortal Kombat,Paul W. S. Anderson,"August 18, 1995","$124,741,822",45.0,60.0,New Line Cinema,Midway
4,Mortal Kombat Annihilation,John R. Leonetti,"November 21, 1997","$51,376,861",4.0,11.0,UNKNOWN,UNKNOWN
...,...,...,...,...,...,...,...,...
82,Fate/stay night: Heaven's Feel II. lost butterfly,Tomonori Sudō,"January 12, 2019","$19,790,000",0.0,0.0,Aniplex,Type-Moon
83,Pokémon: Mewtwo Strikes Back Evolution,Kunihiko YuyamaMotonori Sakakibara,"July 12, 2019","$19,273,056.53",0.0,0.0,TohoViz Media,Nintendo
84,NiNoKuni,Yoshiyuki Momose,"August 23, 2019","$2,000,000",0.0,0.0,"OLM, Inc.",Bandai Namco Entertainment
85,Fate/stay night: Heaven's Feel III. spring song,Tomonori Sudō,"March 28, 2020","$19,252,497",0.0,0.0,Aniplex,Type-Moon
86,Pokémon the Movie: Secrets of the Jungle,Tetsuo Yajima,"December 25, 2020","$23,600,000",0.0,0.0,TohoViz Media,Nintendo

In [22]:
# check for NaN values
print(df['Worldwide box office'].isna().sum())
print(df['Rotten Tomatoes'].isna().sum())
print(df['Metacritic'].isna().sum())

1
3
2

In [27]:
df['Worldwide box office'].value_counts()

Worldwide box office
$38,912,465       1
$1,361,952,674    1
$28,327,512.61    1
$29,103,608.85    1
$20,867,919       1
                 ..
$52,302,796       1
$240,004,424      1
$300,228,084      1
$336,365,676      1
$23,600,000       1
Name: count, Length: 86, dtype: int64

In [40]:
# Specify the file path where you want to save the CSV file
file_path = "/Users/merryxmm7/Documents/GitHub/SQL_Quest/MbasedonV.csv"

# Save the DataFrame as a CSV file with UTF-8 encoding
df.to_csv(file_path, index=False, encoding='utf-8')